spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: PlavDolgVdal0
    driverClassName: org.postgresql.Driver